### ISSUE TITLE
Boilerplate project ToDo

### ISSUE THREAD

**Issue by saeedmrz** [saeedmrz/boilerplate#2]
ToDo List:

- [x] Start Repo :tada:
- [x] Folder architecture.
- [x] Create api-client.js file to handle requests to the server.
- [x] Create useAsync hook to handle Async calls.
- [x] Add SASS to create utilities, components, etc. To maintain our CSS.
- [x] postcss-preset-env to convert modern CSS into something most browsers can
      understand.
- [ ] Documentation - Folder structure
- [ ] Documentation - PWA
- [ ] Documentation - React-JS
- [ ] Documentation - Test
- [x] Build projects board
- [ ] Setup github CI
- [x] Enforcing Standards (Prettier, ESLint, Husky, Lint-Staged, Git Hooks)
